apiVersion: v1
kind: Secret
metadata:
  name: my-es-secret
  labels:
    app: my-nginx-app
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  password: {{ .Values.password | b64enc | quote }}